### ISSUE TITLE
[Feature] Support font-size when copying cell contents from Excel on Windows System

### ISSUE THREAD

**Issue by yuhongz** [dream-num/univer#1404]
### Initial checklist

- [X] Is this really a problem?
- [X] I have searched the Github Issues for similar issues, but did not find anything.

### Problem

as Title

### Solution

Using `event.clipboardData` to read the 'font-size' when copy from Excel on WIN.

### TODOs

- [x] All paste behavior from the shortcut should use native clipboard event @wzhudev
