### ISSUE TITLE
[Feature Ticket] Refactor paragraph layout

### ISSUE THREAD

**Issue by Jocs** [dream-num/univer#1582]
# [Feature Ticket] Refactor paragraph layout

Assignees:
* Shaper: @Jocs 
* Engineers: @Jocs 
* Designer: @Eelson
* QA: @zhaolixin7

### Resources

* [PRD](https://xyrau6itjm.feishu.cn/docx/BajJdKv1zo0bk5xQhdbcTMR5nwh)

### Problem

为了实现后续功能需求，比如段落align（left、center、right）、justify 等，段落的首行缩进、悬挂等。因此通过本需求对 Doc 的段落排版做出一些调整和重构

### Time Budget

This ticket is expected to be completed in **4** weeks, released in version **0.1.5**, around **Apr 15th**.

### Solution

实现[W3C 中文排版需求](https://www.w3.org/TR/clreq/)中关于“行内文字排版处理”的规范，对齐 Word 段落排版功能，具体需要实现和对齐的功能如下：
1. 关于标点符号的特殊处理
  1. 行首行尾禁则：点号（顿号、逗号、句号、冒号、分号、叹号、问号）、结束引号、结束括号、结束双书名号（书名号乙式）、连接号、间隔号、分隔号不能出现在一行的开头。开始引号、开始括号、开始单双书名号等符号，不能出现在一行的结尾；
  2. 标点符号宽度调整
    1. 连续标点符号的调整：如果任意两个相邻标点符号占用2个字宽，应当缩减成1.5个字宽。在此原则上，允许排版风格进一步调整让两个符号只占1个字宽；
    2. 行首行尾标点挤压：原本占一个字宽的标点出现在行尾时，应缩减该符号末侧二分之一个汉字大小的空白；
  3. 行尾点号悬挂：通常，行尾只可悬挂一个点号；适合行尾悬挂的点号有顿号、逗号及句号。简体中文排版中，其余点号因其字面分布偏向被标注文字的一侧、字面始端，也可进行行尾悬挂配置；
2. 中西文混排处理：汉字与西文字母、数字间使用不多于四分之一个汉字宽的字距或空白。但西文出现在行首或行尾时，则无须加入空白；
3. 行内调整：在行超过可容纳宽度时需要进行“挤压处理”，在行宽度少于可容纳宽度并且两端对齐时，需要进行拉伸处理，具体可参考 [文本排版调研](https://xyrau6itjm.feishu.cn/docx/UKOodqXcZoPW14xiRKzc3JzFnEq)；
4. 段落间距、行间距及段落首行缩进、悬挂等

### No-gos

* 本需求不包括 float layout，这会在之后的 Feature Ticket 中

### Resources

* [Technical research](https://xyrau6itjm.feishu.cn/docx/UKOodqXcZoPW14xiRKzc3JzFnEq)

### TODOs

- [x] 部分数据结构调整和设计
  - [x] 做一些调整来支持“挤压处理”和“拉伸处理” #1612 
  - [x] 段落 layout 流程设计 #1602 
- [x] 标点符号特殊处理 #1626 
  - [x] 行首行尾禁则（linebreak 中已经支持，只需要验证下）
  - [x] 连续标点符号的调整
  - [x] 行首行尾标点挤压
  - [x] 行尾点号悬挂
- [x] 中西文混排（这个之前已经实现了，这次需求中需要调整和优化）#1626
  - [x] 汉字与西文字母、数字间使用不多于四分之一个汉字宽的字距或空白
- [x] 行内调整
  - [x] 段落 align 排版
  - [x] 段落 align 菜单功能
  - [x] 双端对齐
- [x] 段落样式（本次需求只做排版，不包括功能）
  - [x] 首行缩进
  - [x] 悬挂
  - [x] 段前、段后、行间距
