### ISSUE TITLE
[Feature Ticket] Refactor of text shaping and support kerning

### ISSUE THREAD

**Issue by Jocs** [dream-num/univer#1755]
Assignees:
- Shaper: [@Jocs](https://github.com/Jocs)
- Engineers: [@Jocs](https://github.com/Jocs)
- Designer: [@Eelson](https://github.com/Eelson)
- QA: [@zhaolixin7](https://github.com/zhaolixin7)

#### Resources

- [Text Shaping 重构-支持 kerning 等特性](https://xyrau6itjm.feishu.cn/docx/AMgOdC1mkoT55px8XF6ciD7EnVf)

#### Problem

At present, Text Shaping in the project relies on the measureText method of canvas context2D, and measureText does not contain information about kerning and ligature when measuring a single glyph, so it cannot support related features such as kerning and ligature in typography

#### Time Budget

This ticket is expected to be completed in 1 weeks, released in version 0.1.6, around Apr 15th.

#### Solution

Harfbuzz is a popular text shaping engine on the market, supports OpenType, Apple Advanced Typography, etc., and is used in Android, Chrome, Firefox and other applications.

Later, we investigated opentype.js, a font parsing and editing library that supports kerning and ligatures, and can also be used for text shaping, although the typographic features are not as much as harfbuzz, but it can also meet our current needs, and the performance is due to measureText.

Therefore, opentype.js will be used for text shaping

Text Shaping is divided into the following steps:

Step 1. Text shaping the entire content of the paragraph, content -> glyphs (glyphs need to contain location information so that it can correspond to breakpoints)

  1. Determine whether you have permission to load the font, if not, skip the following steps and fall back to measureText
  2. Preload all fonts
  3. Divide the text of the paragraph into different chunks according to the style and font, and each chunk contains the same style and font
  4. According to the combination of style and font family, from the font library, blur match the best font
  5. Perform a shaping of the chunk text, and if the resulting glyphs contain notdef glyphs, repeat step c according to the fallback font familys list until the correct glyphs are generated (font fallback strategy)

Step 2. According to the Unicode linebreak algorithm, get all the points and breakpoints that may break the line

Step 3. Get the shapedText {word: string, glyphGroup: Glyph[]} list based on the glyphs and breakpoints obtained above

  1. If you have permission to load fonts, use opentype.js, otherwise use measureText
  2. Divide glyphs into shapedText list according to breakpoints based on the location information in breakpoints
  3. Shaping compatibility is also needed here, if there is a glyph with notdef in glyphs, fall back to measureText

#### Rabbit Holes

No-gos
- This requirement will support kerning, but will not support ligature, and the underlying layer will retain support for ligature capabilities

#### Resources
- [Text Shaping 重构-支持 kerning 等特性](https://xyrau6itjm.feishu.cn/docx/AMgOdC1mkoT55px8XF6ciD7EnVf)

#### TODOs
- [x] Font handling and fallback mechanics
  - [x] Font loading capability: preload and load specified fonts
  - [x] Ability to fuzzy font matching, match the best font based on font family and style, font weight, etc
- [x] Text Shaping
  - [x] Refactored text shaping to support the use of the new shaping engine with window.queryLocalFonts support and user authorization
  - [x] The ability to font fallback
- [x] A pop-up window for the user to authorize access to the local font
- [x] Under the new text shaping, a variety of styles NEED test and reimplement
  - [x] italic、bold、underline etc
