### ISSUE TITLE
[Feature Ticket] Image layout

### ISSUE THREAD

**Issue by Jocs** [dream-num/univer#1990]
# [Feature Ticket] Image layout in doc

Assignees:
* Shaper: @Jocs 
* Engineers: @Jocs 
* Designer: @Eelson
* QA: @zhaolixin7

### Resources

* [PRD](https://xyrau6itjm.feishu.cn/docx/QMq2dP5sIocUHIxi5GocMLSwnjg)

### Problem

Images are the basic functions of documents, and this feature ticket mainly includes the layout of images, including the following layout forms:

- Embedded in text
- wrapping text
- splitting text
- placed in front (behind) of text

### Time Budget

This ticket is expected to be completed in **2** weeks, released in version **0.1.10**, around **May 2th**.

### Solution

Please refer to PRD above.

### No-gos

1. Image insertion methods do not include: drag and drop image insertion, copy and paste image, and insert network image
2. It does not include the adjustment of color change, transparency, brightness, and contrast of the image
3. Does not include the frame, style, and cropping of the image
4. Excluding image size and rotation: Adjust image size, ratio (fixed aspect ratio), and rotation angle

### Resources

* [tech doc](https://xyrau6itjm.feishu.cn/docx/QMq2dP5sIocUHIxi5GocMLSwnjg)
https://xakbyahbro.feishu.cn/mindnotes/Xc2Dbr5vpmlHkmnVsTScxM9FnV3#mindmap
### TODOs

- [x] Change aware incremental layout
- [x] Embedded in text
- [x] Wrapping text
- [x] Splitting text
- [x] Placed in front (behind) of text
