### ISSUE TITLE
[Ticket] refactor modules to support disposing and adding units

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#2089]
* Shaper: @wzhudev 
* Engineers: @wzhudev @lumixraku @Dushusir @yuhongz 
* QA: @zhaolixin7 

### Problem

For a long time, when we write controllers and services, we have made the assumption that only one unit exists and that no additional units would be created afterward. However, this assumption is no longer valid. When we dispose of one unit and create another, certain modules fail to function correctly, leading to memory leaks.

- Rendering
- Formula
- Others?

### Time Budget

This ticket is expected to be completed in **1** weeks, released in version **0.1.9**, around **May 9th**.

### Solution

* For render controllers, we should migrate them to `RenderUnit`.
* For other modules, we should use `IUniverInstanceService.getUnitOfTypeAdded$` and `IUniverInstanceService.getUnitOfTypeDisposed$` . 

![image](https://github.com/dream-num/univer/assets/12122021/567274ea-bf11-450c-b410-a9cc980c9d3e)

### No-gos

- Would not support rendering multi render units on the same canvas at the current time.

### Resources

- Push commits to `refactor/render-unit` branch.

### TODOs

- [x] Rendering-related modules
  - [x] `RenderUnit` `RenderController` You can refer to `HeaderUnhideRenderController` for this section
    - [x] `SheetContextMenuController` @yuhongz 
    - [x] `HeaderMenuController` @yuhongz 
    - [x] `AutoFillController` @yuhongz 
    - [x] `FormatPainterController `@yuhongz
    - [x] `HeaderMoveController` @yuhongz 
    - [x] `HeaderResizeController` @yuhongz 
    - [x] `HoverController` @lumixraku 
    - [x] `SelectionRenderService` @wzhudev 
    - [x] `ZoomController` @wzhudev 
    - [x] `ScrollController` @wzhudev 
    - [x] `SelectionController` @wzhudev 
    - [x] `SpreadsheetColumnHeader` @wzhudev 
    - [x] `SpreadsheetRowHeader` @wzhudev
    - [x] `MoveRangeController` @wzhudev  
    - [x] `FormulaEditorShowController` @wzhudev 
    - [x] `SheetsFilterRenderController` @wzhudev 
    - [x] `CellAlertController` @lumixraku 
    - [x] `CellCustomRenderController` @lumixraku 
    - [x] `MarkSelectionController` @lumixraku 
    - [x] `ForceStringRenderController` @lumixraku 
    - [x] `ForceStringAlertController` @lumixraku 
  - [ ] `SheetSkeletonManagerService` @wzhudev After other migrates complete 
- [x] Formula related modules @Dushusir 
- [x] Fix memory leaking
  - [x] `Worksheet` @wzhudev 
  - [x] `SpreadsheetSkeleton`  @wzhudev 
- [x] Documentation
  - [x] How to dispose a unit and add another unit @wzhudev 
  - [x] Introduction to `RenderUnit` & `RenderController` @wzhudev
  - [x] Example @Dushusir

**Comment by wzhudev** [comment]
Refactor of `SheetSkeletonManagerService` is rescheduled.
