### ISSUE TITLE
[Feature Ticket] Hyphenation in paragraph text layout

### ISSUE THREAD

**Issue by Jocs** [dream-num/univer#2201]
* Shaper: @Jocs  
* Engineers: @Jocs 
* QA: @zhaolixin7 

### Resources

- https://xyrau6itjm.feishu.cn/docx/WmdjdSwN3okg0cx4Cpcc3xnanNc

### Problem

Currently, Univer does not perform word segmentation(hyphenation) when typesetting English and other Western languages. Therefore, when aligning both ends, there will be a large gap between words. It is difficult for users to read and it is not beautiful. Therefore, through Use hyphens for word segmentation to make paragraph layout more beautiful and practical

### Time Budget

This ticket is expected to be completed in **1.5** weeks, released in version **0.1.11**, around **May 23th**.

### Solution

Add hyphenation extension to LineBreaker. When obtaining break points through LineBreaker, add possible break points of hyphenation. When performing a line break, if it is a hyphenation break point, add a hyphen "-" at the end of the line.

### Rabbit Holes

If the paragraph language is automatically detected, there may be certain misjudgments.

### No-gos

This requirement only includes layout according to document settings, and does not include the implementation of paragraph segmentation-related functions (that is, it does not include paragraph settings and document settings)

### Resources

- https://xyrau6itjm.feishu.cn/docx/WmdjdSwN3okg0cx4Cpcc3xnanNc

### TODOs

- [x] Paragraph language auto detection if text run lang is omited.
- [x] Add word breaking plug-in to Line breaker.
- [x] Hyphen word breaking, adding a hyphen at the end of the line.
- [x] Consecutive hyphen restrictions(consecutiveHyphenLimit).
- [x] Do all capital letters need to be segmented(doNotHyphenateCaps).
- [x] Setting and function implementation of hyphenation zone(hyphenationZone).
