### ISSUE TITLE
August Iteration: Architecture & Toolchain

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#32]
For participants: Checkout out working branches from `dev` and file pull requests to it.

## Architecture

- [x] Use DI to refactor the architecture @dream-num/dream 
  - [x] Adopt `@wendellhu/redi` @wzhudev 
  - [x] Remove dependency on `Context` `SheetContext` and `this._plugin` from all base-sheet & sheet-ui plugins @wzhudev 
  - [x] Remove dependency on `Context` `SheetContext` and `this._plugin` from all other upper-level plugins @Dushusir team
    - [x] sheets-plugin-numfmt @eiji-th 
    - [x] sheets-plugin-find @tonytonychopper123 
    - [x] sheet-plugin-formula @Dushusir 
    - [x] sheets-plugin-operation @tonytonychopper123
    - [x] sheets-plugin-image @eiji-th
    - [x] sheets-plugin-import-xlsx @Dushusir
    - [x] sheets-plugin-filter @Dushusir
    - [x] UI context: sheets-plugin-numfmt @eiji-th 
    - [x] UI context: sheets-plugin-find @tonytonychopper123 
    - [x] UI context: sheet-plugin-formula @Dushusir 
    - [x] UI context: sheets-plugin-operation @tonytonychopper123
    - [x] UI context: sheets-plugin-image @eiji-th
    - [x] UI context: sheets-plugin-import-xlsx @Dushusir
    - [x] UI context: sheets-plugin-filter @Dushusir
  - [x] Remove dependency on `context` in core package @wzhudev
  - [x] Refactor UniverDoc & UniverSlide as well @wzhudev 
- [ ] Redesign command system @wzhudev
  - [x] Basic command and undo redo mechanism and documentation @wzhudev #58 
  - [ ] Decompose mutating methods on `Worksheet` `Workbook` `Range` `RangeList` etc to new command system #61 
- [ ] Redesign UI system @wzhudev @jikkai #62 

## Engineering

- [x] Remove plugin packages those are actually blank @Dushusir 
- [x] Add `noImplicitOverride` to all tsconfig files
- [x] Add `CODEOWNERS` file @dream-num/dream 
- [ ] Fix ts errors and make unit tests pass @dream-num/dream 
    - [ ] ts eslint error: sheets-plugin-numfmt @eiji-th 
    - [x] ts eslint error: sheets-plugin-find @tonytonychopper123 
    - [x] ts eslint error: sheet-plugin-formula @Dushusir 
    - [x] ts eslint error: sheets-plugin-operation @tonytonychopper123
    - [ ] ts eslint error: sheets-plugin-image @eiji-th
    - [x] ts eslint error: sheets-plugin-import-xlsx @Dushusir
    - [x] ts eslint error: sheets-plugin-filter @Dushusir
- [ ] #67 @jikkai 
- [ ] (optional) Remove all unnecessary static methods and properties @dream-num/dream 
- [ ] Fix circular dependency and prevent it from happening
  - [ ]  Use `dpdm` to identify circular imports and fix them manually @dream-num/dream 
  - [ ] (optional) Remove all `index.ts` files @dream-num/dream 
  - [x] Enable `import/no-cycle` in eslint @wzhudev 
  - [x] Add eslint to CI @wzhudev 
- [ ] Check for typos, like `genname` @eiji-th
- [ ] Add commit-msg and pre-commit git hooks @Gggpound 
- [x] Forbid pushing to `dev` branch directly @wzhudev 

## Community

- [ ] Fix contribution guide and add issue template @jikkai 
  - [ ] Contributing guide @jikkai 
  - [x] Issue template @jikkai

**Comment by wzhudev** [comment]
Unfinished tasks would be continued in #90.
