### ISSUE TITLE
MVP Features

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#73]
To the developers who will be responsible for implementing these features, please ensure that:

* All related commands, mutations, operations, menu items, and models are thoroughly unit tested.
* The undo-redo functionality is working correctly and without any issues.
* All design requirements have been met in the implementation.
* Your pull request (PR) is reviewed by another member of the team before merging.

---

## Milestone 1 - Basic Sheet Features

To reach this milestone, we should diligently implement essential components and fundamental features, with the aim of providing a solid foundation to support future advancements and developments.

Deadline *October 21th, 2023*

- [x] #117 lead by @jikkai, participants @Dushusir @tonytonychopper123
  - [x] #154 @yuhongz 
- [x] #70 @jikkai 
- [x] worksheet 
  - [x] #147
  - [x] Draggable tab @jikkai 
- [x] #148 @Dushusir @tonytonychopper123 
- [x] #149 @wzhudev 
- [x] #124 @wzhudev 
- [x] #150 @wzhudev 
  - [x] Support multi selections
  - [x] Change selections with keyboard and cursor
- [x] #151 @yuhongz 

## Milestone 2 - Features II

- [x] #152 @DR-Univer @Jocs 
    - [x] copy paste
    - [x] rich text editing
- [x] Packaging format
- [ ] #153 @DR-Univer @Dushusir @tonytonychopper123 
- [ ] Facade layer 
- [ ] Data format
- [ ] Filling
- [ ] Sorting
- [ ] Data protection
- [ ] Menu grouping and toolbar collapsing
- [ ] Import & export

## Milestone 3 - Advanced Features & Facade
