### ISSUE TITLE
September Iteration: Finish Refactoring

### ISSUE THREAD

**Issue by wzhudev** [dream-num/univer#90]
For participants: Checkout out working branches from `dev` and file pull requests to it.

## Architecture

- [x] Redesign command system @wzhudev
  - [x] Basic command and undo redo mechanism and documentation @wzhudev #58 
  - [x] Decompose mutating methods on `Worksheet` `Workbook` `Range` `RangeList` etc to new command system #61 
- [x] Redesign UI system @wzhudev @jikkai #62 
- [ ] #69 @wzhudev 
- [x] #65 @DR-Univer 
- [x] #109 @wzhudev @DR-Univer 

## Engineering

- [ ] #67 @jikkai 
- [ ] (optional) Remove all unnecessary static methods and properties @dream-num/dream 
- [ ] Fix circular dependency and prevent it from happening
  - [ ]  Use `dpdm` to identify circular imports and fix them manually @dream-num/dream 
  - [ ] (optional) Remove all `index.ts` files @dream-num/dream 
  - [x] Enable `import/no-cycle` in eslint @wzhudev 
  - [x] Add eslint to CI @wzhudev 
- [ ] Check for typos, like `genname` 
- [x] Forbid pushing to `dev` branch directly @wzhudev 

## Community

- [ ] Fix contribution guide and add issue template @jikkai 
  - [ ] Contributing guide @jikkai 
  - [x] Issue template @jikkai
